import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav style={{ padding: '10px', background: '#eee' }}>
        <a href="/" style={{ marginRight: '10px' }}>홈</a>
        <a href="/about" style={{ marginRight: '10px' }}>소개</a>
        <a href="/blog">블로그</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
