import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LogoutButton from './components/LogoutButton';
import { createServerSupabaseClient } from '../lib/supabase-server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createServerSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav style={{ padding: '10px', background: '#eee' }}>
          <a href="/" style={{ marginRight: '10px' }}>홈</a>
          <a href="/about" style={{ marginRight: '10px' }}>소개</a>
          <a href="/blog" style={{ marginRight: '10px' }}>블로그</a>
          {user ? (
            <>
              <span style={{ marginRight: '10px' }}>{user.email}님</span>
              <LogoutButton />
            </>
          ) : (
            <>
              <a href="/login" style={{ marginRight: '10px' }}>로그인</a>
              <a href="/signup" style={{ marginRight: '10px' }}>회원가입</a>
            </>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}